FlyleafLib/Controls/WPF/FlyleafHost.cs, FlyleafLib/Utils/NativeMethods.cs
This has various benefits:
* Overlay is positioned relative to Surface window automatically, you just need to set its position to (0,0)
* Surface is positioned relative to Owner window, you just need to find Left and Top locations of FlyleafHost.
* Should fix the weird bug you commented in the code:
> Overlay maximized on Screen 2 when Surface maximized on Screen 1
* User is not able to move these child windows using shortcut keys, without moving the parent window. They'll be recognized as controls instead of independent windows.
* You don't need to handle minimized window state manually anymore.
The only problem is the previous code was assuming that it needs to position the Overlay and Surface relative to screen, not their parent windows. I tried to change this every where I could but …
=> Set WS_CHILD to Overlay and Surface windows

FlyleafLib.Controls.WPF/Resources/PopUpMenu.xaml, FlyleafLib/Engine/Engine.Audio.cs, FlyleafLib/Engine/Engine.Video.cs, FlyleafLib/Engine/Engine.cs, FlyleafLib/Engine/VideoDeviceEnumerator/IVideoDevice.cs, FlyleafLib/Engine/VideoDeviceEnumerator/IVideoFormat.cs, FlyleafLib/Engine/VideoDeviceEnumerator/VideoDevice.cs, FlyleafLib/Engine/VideoDeviceEnumerator/VideoDeviceEnumerator.cs, FlyleafLib/Engine/VideoDeviceEnumerator/VideoFormat.cs, FlyleafLib/Engine/VideoDeviceEnumerator/VideoFormatsViaMediaSource.cs, FlyleafLib/FlyleafLib.csproj, FlyleafLib/MediaFramework/MediaDemuxer/Demuxer.cs, Samples/FlyleafPlayer (WPF Control) (WPF)/Dictionary.xaml
Engine: Add enumerator for usb webcams.
Demuxer: Add support for dshow device parameters.
FlyleafPlayer (WPF Control): Add "Open Device" menu.
Issues:
1. IMPORTANT! Usb webcam has noticeable latency. Setting MaxLatency to 1 and then to 0 fixes this. What is the reason?
2. Flyleaf does not play NV12. NV12 throws -5 on avformat_open_input.  Maybe there are other not supported webcam video formats?
3. Should ffmpeg.av_dict_free(ref AVDictionary*) be used to dispose of avopt in Demuxer?
=> DirectShow usb webcam improvements.

FlyleafLib/MediaFramework/MediaDevice/AudioDevice.cs, FlyleafLib/MediaFramework/MediaDevice/DeviceBase.cs, FlyleafLib/MediaFramework/MediaDevice/VideoDevice.cs, FlyleafLib/MediaFramework/MediaDevice/VideoDeviceStream.cs
Enables more concise access to VideoDeviceStream properties:
```
var height= Engine.Video.CapDevices[0].Streams[0].FrameSizeHeight;
```
instead of:
```
var height = ((VideoDeviceStream)Engine.Video.CapDevices[0].Streams.First()).FrameSizeHeight;
```
=> Use generics for DeviceBase DeviceStreamBase.

FlyleafLib/MediaFramework/MediaRenderer/Renderer.Present.cs
Have found from a lot of playing static images that sometimes they are not successfully presented and just leave a black screen.
Narrowed down to a line of code in the renderer that only allows 5mS for the lock on the device to become available otherwise the frame is dropped. Clearly there is the odd occasion where 5mS is not quite enough. This could be exacerbated by having multiple players running simultaneously where images are being opened on all players at the same time. (Which is what I was doing).
This PR increases the time to 100mS, but only for the very first frame.
=> Allow more time for first frame - critical for static images to be reliably displayed

FlyleafLib.Controls.WPF/SubtitleText.cs, FlyleafLib.Controls.WPF/Themes/FlyleafME.xaml, Samples/FlyleafPlayer (WPF Control) (WPF)/MainWindow.xaml
The subtitle text can be improved to work as other video players do and outline the entire text instead of a drop shadow. Based on this lengthy discussion on stack overflow
https://stackoverflow.com/questions/93650/apply-stroke-to-a-textblock-in-wpf
Also enables customizing outline thickness if you wanted to.
=> Outlined subtitle text, replace dropshadow effect with formatted text geometry

FlyleafLib/MediaFramework/MediaDemuxer/Demuxer.cs
If a stream or a file has valid video tracks, but the last video track is corrupt, empty or otherwise unreadable, the whole stream or file is marked as not having video.
This allows the player to support more streams and video files.
Can also consider adding a check so that invalid video tracks are not added to the available streams.
=> Allow streams/files with at least one good video track

FlyleafLib/Controls/WPF/FlyleafHost.cs, FlyleafLib/Controls/WPF/PlayerDebug.xaml, FlyleafLib/MediaFramework/FFmpegBindings/ffmpegEx.cs, FlyleafLib/MediaFramework/MediaContext/DecoderContext.Open.cs, FlyleafLib/MediaFramework/MediaRenderer/Renderer.PixelShader.cs, FlyleafLib/MediaPlayer/Player.Keys.cs, FlyleafLib/MediaPlayer/Player.Open.cs, FlyleafLib/Plugins/PluginHandler.cs, Samples/FlyleafPlayer (WPF Control) (WPF)/MainWindow.xaml, Samples/FlyleafPlayer (WPF Control) (WPF)/MainWindow.xaml.cs
- Renderer: Fixes an access violation with broken files [Fixes #424]
- Subtitles: Prevents Local/Online Search for 'small' duration videos (less than 25 minutes)
- VideoDecoder: Fixes (possible) an issue with the codec's announced rotation
- Player.Keys: Allows overwriting existing keys instead of throwing an exception
- Player: Introduces Opening event
- FlyleafHost.Wpf: Activates Surface/Overlay window after DragNDrop
- PlayerDebug: Adds full Url
- Samples.FlyleafPlayer: Adds Photo Viewer / Slide Show support
=> Sync with local

FlyleafLib/MediaFramework/MediaDecoder/VideoDecoder.cs
When playing network streams, if the video changes the player does not update width/height.
This change checks when receiving frame from decoder if width or height has changed.
How to test:
1. Start a network stream, e.g.: `ffmpeg -re -i my_test_video.ts -c copy -f mpegts udp://238.255.255.255:1234`
2. Start playback with the url
3. After the player has started playing run `taskkill -f -im ffmpeg.exe && ffmpeg -re -i my_other_test_video.ts -c copy -f mpegts udp://238.255.255.255:1234`
This assumes the two videos has different resolutions
=> Fix video changing on network stream not updating player to correct width/height

FlyleafLib/MediaPlayer/Player.Screamers.cs
fix: Infinite sleep occurs only for some rtsp videos
=> fix: Infinite sleep occurs only for some rtsp videos

FlyleafLib/Controls/WPF/FlyleafHost.cs
Added two new events to wpf FlyleafHost:
OnSurfaceDrop and OnOverlayDrop
These events will be invoked and checked if anything handled the event before trying to solve the events internally.
This will enable users to have custom handling of drop events (like viewmodels)
=> Added custom drop events to wpf FlyleafHost

FlyleafLib/MediaFramework/MediaDecoder/DataDecoder.cs
When connecting to a video stream instead of a file with a data track, disposing the player would trigger a null ref exception because the DataDecoder wouldn't exit when disposed and thus the DataDecoder would read the demuxer field which is null
=> Fix DataDecoder null ref on demuxer when disposing player

FlyleafLib/MediaFramework/MediaDecoder/VideoDecoder.cs
When speed is changed prior to loading the video stream it will crash
Bug introduced when adding MaxOutputFps
=> Don't change the speed of the video decoder if the stream is not loaded

FlyleafLib/MediaPlayer/Player.Open.cs, FlyleafLib/Utils/Utils.cs
Added support for direct opening of windows link files.
I thought it needed to be supported on the library side because it also needs to work with drag-and-drop.
Since the following method of using COM did not work without a single-threaded app,
https://stackoverflow.com/questions/43980088/is-there-a-way-in-c-sharp-to-find-the-current-location-of-a-shortcut-target-prog
I chose the following implementation.
https://stackoverflow.com/questions/64126236/reading-the-target-of-a-lnk-file-in-c-sharp-net-core
I have confirmed that it can be opened from drag-and-drop and right-click in WPF's FlyleafPlayer.
=> Player: Adds support for opening windows link files

FlyleafLib/Engine/Engine.FFmpeg.cs, FlyleafLib/Utils/Logger.cs
This PR modifies the logger class to add support for pluggable logging engines to replace the inbuilt flyleaf logger if desired. This opens the door for circular log sets, better autoflush behavior and other log maintenance features, using the standard MS logging interface, as implemented by packages such as nlog.
The change has been made in a non-breaking way, in that if an app does not set the new static class variable to an iLogger instance, the existing functionality rules.
In this PR I chose not to change the current enum values for the various log levels, but they don't match the iLogger enums, and so I perform an internal conversion as required.
There is one thing that probably needs to be tweaked here: the logging code for ffmpeg level logging - I removed the timestamp on the …
=> Added support for pluggable logger implementation

Plugins/YoutubeDL/YoutubeDL.cs
Fixed video stream selection logic for Youtube playback.
Currently after width and height, the video streams are sorted in descending order by fps,
but some youtube videos may prefer vcodec as vp09 and protocol as m3u8.
I have confirmed that when this combination is used, seek is not possible at all.
error log
```
FFmpeg|Error  |[mov,mp4,m4a,3gp,3g2,mj2 @ 00000202ae334580] root atom offset 0xffffffffffffffff: partial file
23.05.28.832 | Warn  | [#1]     [Demuxer:  Main] Invalid data found when processing input (-1094995529)
23.05.28.833 | Error | [#1]     [Demuxer:  Main] Too many errors!
23.05.28.908 | Debug | [#1]     [Player        ] OnBufferingCompleted (Error: Buffering failed)
23.05.28.909 | Debug | [#1]     [Player        ] [SCREAMER] Finished (Status: Paused, Error: Playback …
```
=> Plugins.YoutubeDL: Improved video stream selection for YT

FlyleafLib/MediaPlayer/Player.Open.cs, FlyleafLib/Utils/Utils.cs
This PR #505 supported lnk file resolution on Windows,
but as a result of using own implementation, we were not able to support shortcuts to external file systems.
I chose to use COM implementation by using dynamic with the following reference.
https://stackoverflow.com/questions/8660705/how-to-follow-a-lnk-file-programmatically/49198242#49198242
Check with the following files. 
* link file towards C drive
* link file towards NAS
* invalid link file
* It outputs an error log and results in an avformat_open_input error.
=> Player: Fixes an issue with resolving windows link files in external fs

FlyleafLib/Engine/Config.cs
Fixed a problem where viewport was not updated when custom aspect ratio values were updated.
1. Open FlyleafPlayer WPF and open video
2. Open settings and change "Aspect Ratio" to custom
3. Set "Custom Ratio" to "1:1" but viewport is not updated
1. Do Bug1 step and press "Save"
2. Reopen settings and change "Aspect Ratio" to "Keep"
3. Restart and open settings
4. bug: "Aspect Ratio" is set to "Custom" instead of "Keep"
Stop setting AspectRatio to "Custom" when updating CustomAspectRatio and update viewport only when Custom is used.
The other code is written with a single line of setter, so I aligned it with that.
=> Config: Update viewport when Config.Video.CustomAspectRatio changes

FlyleafLib/MediaFramework/MediaDemuxer/Demuxer.cs, FlyleafLib/MediaPlayer/Player.cs
I noticed that the chapter information in the context menu is not updated when another video is opened in the WPF sample player, so I changed it to from List to ObservableCollection.
Also added a change notice to make Player.Chapters bindable. For example, this change notice is needed when adding Ticks to Slider to player.
Example Ticks
```csharp
<Slider    
Grid.Column="1" 
Ticks="{Binding Player.Chapters, Converter={StaticResource ChaptersToTicksConverter}}" />
[ValueConversion(typeof(IEnumerable<Chapter>), typeof(DoubleCollection))]
public class ChaptersToTicksConverter : IValueConverter
{
public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
{
if (value is IEnumerable<Chapter> chapters)
{
List<double> secs = chapters.Select(c => c.StartTime / …
```
=> Player: Fixes an issue that Chapters changes are not updated

FlyleafLib/MediaPlayer/Player.Extra.cs
A typo was found in Player's ResetAll command and has been corrected.
=> Player: Fixed typo in ResetAll Command

FlyleafLib/MediaPlayer/Player.Keys.cs
The SeekBackward3 Command was already available, but it was not defined in Keys and could not be used, so this was added.
=> Player: Added Seek offset 3 keys

FlyleafLib/MediaPlayer/Player.Keys.cs
ResetAll was a KeyDown event and has been corrected to a KeyUp event.
I think KeyUp is appropriate since it is not executed continuously.
=> Player.Keys: ResetAll should be KeyUp

FlyleafLib/Plugins/OpenSubtitles.cs, FlyleafLib/Utils/Utils.cs
Added support for bitmap subtitles in .sup.
OpenSubtitles is not modified because it supports only srt for text subtitles.
https://github.com/SuRGeoNix/Flyleaf/blob/35ab3473d97025aaeb49cf5ffeb31a7ddd69003d/FlyleafLib/Plugins/OpenSubtitles.cs#L64
I confirmed that it works with sup and sub subtitles.
=> Subtitles: Adds support for .sup bitmap

FlyleafLib/MediaFramework/MediaPlaylist/Playlist.cs
Fixed playlist next and previous button updates not working properly.
1. Open Youtube any playlist URL in Flyleaf WPF Sample
2. Wait until playlist items are added
3. Next playlist item button in FlyleafBar does not appear (bug)
1. Open Youtube any playlist URL in Flyleaf WPF Sample
2. Select next item in playlist from ContextMenu to enable prev/next buttons
4. Press CTRL+Q to reset
5. prev/next buttons in FlyleafBar do not disappear (bug)
=> Playlist: Fix not updating next/prev item when added/reset

FlyleafLib/MediaFramework/MediaDemuxer/Interrupter.cs
I reset the timed out status in the Read interrupter, as it was probably not intended.
When a read timed out, it is necessary to seek to resume playback, but the status is reset at that time, so there seemed to be no problem with the current implementation. However, I don't think it was intended, so it is fixed.
=> Interrupter: Reset timeout state on Read

FlyleafLib/Engine/Globals.cs, FlyleafLib/Engine/Language.cs
Small performance optimizations were made.
Because the call to `obj.Equals()` causes boxing when int, double, or struct of a value type is used in Set<T>, I changed to use `EqualityComparer<T>.Default` to compare.
```
The Default property checks whether type T implements the System.IEquatable<T> interface and, if so, returns an EqualityComparer<T> that uses that implementation. Otherwise, it returns an EqualityComparer<T> that uses the overrides of Object.Equals and Object.GetHashCode provided by T.
```
https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.equalitycomparer-1.default?view=net-8.0
Types that implement `IEquatable<T>` can be compared without boxing, so I also implemented that in the user type structure `AspectRatio`.
Case-insensitive string comparison in …
=> Minor performance optimization for NotifyPropertyChanged, Language
